### ISSUE TITLE
Slither throwing error

### ISSUE THREAD

**Issue by maxsam4** [crytic/slither#177]
Using the eth-security-toolbox docker image, below is the output when I try to run slither on polymath-core repo. branch dev-3.0.0.

```
root@8718b32c7698:~/polymath-core# slither .
INFO:Slither:'truffle compile' running (use --truffle-version truffle@x.x.x to use specific version)
INFO:Slither:
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 556, in main_impl
    (results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 110, in process_truffle
    triage_mode=args.triage_mode)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 58, in __init__
    self._analyze_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 253, in _analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 319, in _analyze_third_part
    self._analyze_variables_modifiers_functions(lib)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 372, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 279, in analyze_content_functions
    function.analyze_content()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/function.py", line 206, in analyze_content
    node.analyze_expressions(self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/cfg/node.py", line 31, in analyze_expressions
    expression = parse_expression(self._unparsed_expression, caller_context)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 385, in parse_expression
    return  parse_call(expression, caller_context)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 283, in parse_call
    called = parse_expression(expression['expression'], caller_context)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 503, in parse_expression
    var = find_variable(value, caller_context, referenced_declaration)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 157, in find_variable
    raise VariableNotFound('Variable not found: {}'.format(var_name))
slither.solc_parsing.expressions.expression_parsing.VariableNotFound: Variable not found: _removeModuleWithIndex

```

The below dockerfile replicates the whole process and the error
```
FROM trailofbits/eth-security-toolbox
USER root

ENV DEBIAN_FRONTEND noninteractive

RUN apt update
RUN apt install wget curl gnupg software-properties-common apt-utils -y

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN add-apt-repository ppa:ethereum/ethereum

RUN apt update
RUN apt install yarn npm solc git-core unzip -y

RUN git clone https://github.com/PolymathNetwork/polymath-core.git

WORKDIR /home/ethsec/polymath-core

RUN git checkout dev-3.0.0
RUN git pull
RUN yarn install

RUN rm contracts/helpers/PolyToken.sol

RUN truffle compile
RUN slither .
```

**Comment by montyly** [comment]
Hi,

Thank you for the detailed report. 

I pushed a temporary fix in the `dev-fix-polymath-core` branch: https://github.com/trailofbits/slither/tree/dev-fix-polymath-core

I will investigate if this fix can be permanent.

**Comment by maxsam4** [comment]
That was fast!

@montyly Thanks for the quick fix, I'll try it over the weekend.

**Comment by maxsam4** [comment]
@montyly I just tried it again but I got the same error
```
(slither-dev) max@max-GF63-8RC:~/Desktop/Ethereum/truffle 5/polymath-core$ slither .
INFO:Slither:'truffle compile' running (use --truffle-version truffle@x.x.x to use specific version)
INFO:Slither:
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/home/max/.local/lib/python3.6/site-packages/slither/__main__.py", line 556, in main_impl
    (results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)
  File "/home/max/.local/lib/python3.6/site-packages/slither/__main__.py", line 110, in process_truffle
    triage_mode=args.triage_mode)
  File "/home/max/.local/lib/python3.6/site-packages/slither/slither.py", line 58, in __init__
    self._analyze_contracts()
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 253, in _analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 319, in _analyze_third_part
    self._analyze_variables_modifiers_functions(lib)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 372, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 279, in analyze_content_functions
    function.analyze_content()
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/function.py", line 206, in analyze_content
    node.analyze_expressions(self)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/cfg/node.py", line 31, in analyze_expressions
    expression = parse_expression(self._unparsed_expression, caller_context)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 385, in parse_expression
    return  parse_call(expression, caller_context)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 283, in parse_call
    called = parse_expression(expression['expression'], caller_context)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 503, in parse_expression
    var = find_variable(value, caller_context, referenced_declaration)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 157, in find_variable
    raise VariableNotFound('Variable not found: {}'.format(var_name))
slither.solc_parsing.expressions.expression_parsing.VariableNotFound: Variable not found: _removeModuleWithIndex
```
I used the `dev-fix-polymath-core` branch to build slither.

**Comment by montyly** [comment]
Hi,

I just tested on a fresh installation, it does work on my side. Maybe it is an issue with your local Slither installation. Did you use virtualenv (see [the developer installation](https://github.com/trailofbits/slither/wiki/Developer-installation))? If you installed both Slither through `pip install slither-analyzer`  and through a git clone/install, that might have generated conflicts.  

Anyway, yesterday we released [0.6.1](https://github.com/trailofbits/slither/releases/tag/0.6.1); it has the fix included. If you update Slither through pip, it should work.

**Comment by maxsam4** [comment]
hey @montyly , I was using a virtualenv. I had slither installed through pip as well so there might have been conflicts. Anyway, I updated the pip version as you suggested but it's still not working. A different error this time, though
```
max@max-GF63-8RC:~/Desktop/Ethereum/truffle 5/polymath-core$ slither --version
0.6.1
max@max-GF63-8RC:~/Desktop/Ethereum/truffle 5/polymath-core$ slither .
INFO:Slither:'truffle compile' running (use --truffle-version truffle@x.x.x to use specific version)
INFO:Slither:
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/home/max/.local/lib/python3.6/site-packages/slither/__main__.py", line 567, in main_impl
    (results, number_contracts) = process_truffle(filename, args, detector_classes, printer_classes)
  File "/home/max/.local/lib/python3.6/site-packages/slither/__main__.py", line 116, in process_truffle
    triage_mode=args.triage_mode)
  File "/home/max/.local/lib/python3.6/site-packages/slither/slither.py", line 58, in __init__
    self._analyze_contracts()
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 253, in _analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 332, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 372, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 279, in analyze_content_functions
    function.analyze_content()
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/function.py", line 218, in analyze_content
    node.analyze_expressions(self)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/cfg/node.py", line 31, in analyze_expressions
    expression = parse_expression(self._unparsed_expression, caller_context)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 442, in parse_expression
    right_expression = parse_expression(expression['rightHandSide'], caller_context)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 389, in parse_expression
    return  parse_call(expression, caller_context)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 290, in parse_call
    arguments = [parse_expression(a, caller_context) for a in expression['arguments']]
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 290, in <listcomp>
    arguments = [parse_expression(a, caller_context) for a in expression['arguments']]
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 404, in parse_expression
    expressions = [parse_expression(e, caller_context) if e else None for e in expression['components']]
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 404, in <listcomp>
    expressions = [parse_expression(e, caller_context) if e else None for e in expression['components']]
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 524, in parse_expression
    right_expression = parse_expression(right, caller_context)
  File "/home/max/.local/lib/python3.6/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 352, in parse_expression
    name = expression[caller_context.get_key()]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by maxsam4** [comment]
upon further inspection, turns out that it's working fine on the `dev-3.0.0` branch but breaking on the branch I am currently working on i.e. `gtm-signed-transfer`. I am almost certain that the culprit is 
```
(investor, fromTime, toTime, expiryTime, signature) = abi.decode(_data, (address[], uint256[], uint256[], uint256[], bytes));
```

More specifically, I think `abi.decode(foo, (bar[]));` breaks your parser. No other parser that I tried was able to parse arrays inside tupples. I had to fix this in solidity-coverage and Federico fixed it in his ANTL parser. I guess, you'll need to fix this as well.

**Comment by montyly** [comment]
That's weird, I can't reproduce your issue.

I pulled the latest `eth-security-toolbox` (which includes Slither 0.6.1), and try your dockerfile, it does work.

Could you try to delete the Truffle `build` directory and run `slither .` again?

**Comment by maxsam4** [comment]
@montyly Please refer my above comment. Sorry for the initial confusion.

**Comment by montyly** [comment]
That's a good catch, thanks!. I will take a look at how to handle this structure.

**Comment by montyly** [comment]
Hi @maxsam4. 
I added the correct support in the `dev` branch (https://github.com/crytic/slither/commit/4640861a1c1d3bf83d5db9d2170389c4f1177886)

`gtm-signed-transfer` was not available anymore, but the current `dev-3.0.0` was triggering the error, and works now.

Sorry for the delay in the fix. If we don't find related parsing issues, the fix will be merged to `master` in the following days.

**Comment by enderphan94** [comment]
Upgrade to the version 0.6.12 fixed this issue.
