### ISSUE TITLE
Error: Source "@openzeppelin/contracts/math/SafeMath.sol" not found: File not found.

### ISSUE THREAD

**Issue by i11m20n** [crytic/slither#640]
The command I executed:
> slither .

My environment: truffle project

error:
Compilation warnings/errors on ./Controller.sol:
./Controller.sol:4:1: Error: Source "@openzeppelin/contracts/math/SafeMath.sol" not found: File not found.
import "@openzeppelin/contracts/math/SafeMath.sol";
^-------------------------------------------------^
./Controller.sol:5:1: Error: Source "@openzeppelin/contracts/token/ERC20/SafeERC20.sol" not found: File not found.
import "@openzeppelin/contracts/token/ERC20/SafeERC20.sol";
^---------------------------------------------------------^
./Controller.sol:6:1: Error: Source "@openzeppelin/contracts/utils/Address.sol" not found: File not found.
import "@openzeppelin/contracts/utils/Address.sol";
^-------------------------------------------------^

Traceback (most recent call last):
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 360, in _run_solc
    ret = json.loads(stdout)
  File "/Users/anonymous/.pyenv/versions/3.7.5/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/anonymous/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/anonymous/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/slither/__main__.py", line 68, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 1040, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 123, in __init__
    self._compile(**kwargs)
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 930, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 152, in compile
    working_dir=solc_working_dir,
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 364, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation ./Controller.sol:4:1: Error: Source "@openzeppelin/contracts/math/SafeMath.sol" not found: File not found.
import "@openzeppelin/contracts/math/SafeMath.sol";
^-------------------------------------------------^
./Controller.sol:5:1: Error: Source "@openzeppelin/contracts/token/ERC20/SafeERC20.sol" not found: File not found.
import "@openzeppelin/contracts/token/ERC20/SafeERC20.sol";
^---------------------------------------------------------^
./Controller.sol:6:1: Error: Source "@openzeppelin/contracts/utils/Address.sol" not found: File not found.
import "@openzeppelin/contracts/utils/Address.sol";
^-------------------------------------------------^

ERROR:root:None
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 360, in _run_solc
    ret = json.loads(stdout)
  File "/Users/anonymous/.pyenv/versions/3.7.5/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/anonymous/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/anonymous/.pyenv/versions/3.7.5/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/slither/__main__.py", line 68, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 1040, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 123, in __init__
    self._compile(**kwargs)
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 930, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 152, in compile
    working_dir=solc_working_dir,
  File "/Users/anonymous/slither-analyzer/env/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 364, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation ./Controller.sol:4:1: Error: Source "@openzeppelin/contracts/math/SafeMath.sol" not found: File not found.
import "@openzeppelin/contracts/math/SafeMath.sol";
^-------------------------------------------------^
./Controller.sol:5:1: Error: Source "@openzeppelin/contracts/token/ERC20/SafeERC20.sol" not found: File not found.
import "@openzeppelin/contracts/token/ERC20/SafeERC20.sol";
^---------------------------------------------------------^
./Controller.sol:6:1: Error: Source "@openzeppelin/contracts/utils/Address.sol" not found: File not found.
import "@openzeppelin/contracts/utils/Address.sol";
^-------------------------------------------------^

**Comment by montyly** [comment]
Hi @i11m20n. Can you share the codebase that you are trying to analyze?

Can you run `npm install` before slither?

**Comment by i11m20n** [comment]
> Hi @i11m20n. Can you share the codebase that you are trying to analyze?
> 
> Can you run `npm install` before slither?

Sorry, I cannot share my code base.

I run `pip install` to install, the version is 0.6.13

**Comment by montyly** [comment]
I see; these errors are usually because:
- Slither is run from `contracts` instead of the top-level directory. In other word, `slither .` must be run from the top-level directory, where  `truffle-config.js` is located
- The dependencies (openzepellin) are not locally installed. `npm install` should fix that

**Comment by i11m20n** [comment]
> I see; these errors are usually because:
> 
> * Slither is run from `contracts` instead of the top-level directory. In other word, `slither .` must be run from the top-level directory, where  `truffle-config.js` is located
> * The dependencies (openzepellin) are not locally installed. `npm install` should fix that

Thank you very much, this solved my problem.

I did execute the `slither .` command in the `contract` dir.

**Comment by Skyge** [comment]
Hey @montyly , met the same error, 
![image](https://user-images.githubusercontent.com/27282380/108033503-0dcab000-706f-11eb-9eed-ed5e9f13d2d5.png)

I have installed the dependencies(openzeppelin) .
And `slither-analyzer` is `0.7.0`, I use the hardhat, it can compile correctly.

**Comment by aviksaikat007** [comment]
I'm still getting this issue @Skyge have you found the solution? I installed the `openzeppelin` library using `npm` & even added  the node modules to path as well
